### ISSUE TITLE
说“游戏非正常退出”

### ISSUE THREAD

**Issue by pp804486734** [pp804486734/www#1]
[11:23:01][main/INFO] Initialized settings.
[11:23:02][UpdateChecker/WARN] Failed to get update url.
java.net.UnknownHostException: huangyuhui.duapp.com
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.<init>(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.http.HttpClient.New(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
    at org.jackhuang.hellominecraft.utils.NetUtils.doGet(NetUtils.java:65)
    at org.jackhuang.hellominecraft.utils.NetUtils.doGet(NetUtils.java:69)
    at org.jackhuang.hellominecraft.utils.UpdateChecker.run(UpdateChecker.java:50)
[11:29:24][AWT-EventQueue-0/INFO] Start generating launching command...
[11:29:25][Game Launcher/INFO] *** Make shell command ***
[11:29:25][Game Launcher/INFO] On making head command.
[11:29:25][Game Launcher/INFO] Java Version: 1.8.0_201
[11:29:25][Game Launcher/INFO] Java Platform: 32
[11:29:25][Game Launcher/INFO] System Platform: 32
[11:29:25][Game Launcher/INFO] System Physical Memory: 8157
[11:29:25][Game Launcher/INFO] On making launcher args.
[11:29:25][Game Launcher/INFO] Starting process
Error occurred during initialization of VM
Could not reserve enough space for 1048576KB object heap
Java HotSpot(TM) Client VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

**Comment by pp804486734** [comment]
不知道什么意思，求解答
